description: Run schedule


inputs:
  token:
    description: Personal Access Token
    required: false
    default: ''


runs:
  using: composite

  steps:
    - uses: li1ht2ay-3es/gi1-ac2io3s@keep-alive
      with:
        token: ${{ inputs.token }}
        auto: true


    - uses: li1ht2ay-3es/gi1-ac2io3s@rebase-repo
      with:
        remote_repo: Smart123s/ItchClaim
        remote_branch: master

        token: ${{ inputs.token }}
        auto: true


    - uses: li1ht2ay-3es/gi1-ac2io3s@keep-alive
      with:
        branch: tester

        token: ${{ inputs.token }}
        auto: true


    - uses: li1ht2ay-3es/gi1-ac2io3s@keep-alive
      with:
        branch: build

        token: ${{ inputs.token }}
        auto: true


    - uses: li1ht2ay-3es/gi1-ac2io3s@keep-alive
      with:
        branch: build-scrape-sales

        token: ${{ inputs.token }}
        auto: true


    - uses: li1ht2ay-3es/gi1-ac2io3s@keep-alive
      with:
        branch: build-scrape-rewards

        token: ${{ inputs.token }}
        auto: true

    
    - uses: li1ht2ay-3es/gi1-ac2io3s@keep-alive
      with:
        branch: build-auto-rating

        token: ${{ inputs.token }}
        auto: true
